void main()
{
    object oPC = GetPCLevellingUp();
    int nCurrentLevel = GetHitDice(oPC);
    int iXP = (nCurrentLevel * (nCurrentLevel - 1) / 2) * 1000;

    if(
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_BASTARDSWORD, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_BATTLEAXE, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_CLUB, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_CREATURE, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_DAGGER, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_DART, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_DIREMACE, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_DOUBLEAXE, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_DWAXE, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_GREATAXE, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_GREATSWORD, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_HALBERD, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_HANDAXE, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_HEAVYCROSSBOW, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_HEAVYFLAIL, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_KAMA, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_KATANA, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_KUKRI, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTCROSSBOW, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTFLAIL, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTHAMMER, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_LIGHTMACE, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_LONGBOW, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_LONGSWORD, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_MORNINGSTAR, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_QUARTERSTAFF, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_RAPIER, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_SCIMITAR, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_SCYTHE, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_SHORTBOW, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_SHORTSPEAR, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_SHORTSWORD, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_SHURIKEN, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_SICKLE, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_SLING, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_THROWINGAXE, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_TRIDENT, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_TWOBLADEDSWORD, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_UNARMED, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_WARHAMMER, oPC) ||
    GetHasFeat(FEAT_EPIC_DEVASTATING_CRITICAL_WHIP, oPC)
    )
    {
        nCurrentLevel = nCurrentLevel - 1;
        //Level Formula: (level * (level - 1) / 2) * 1000
        SetXP(oPC, iXP);
        SendMessageToPC(oPC, "Devastating Critical is not allowed.");
    }
}
